dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.0.0
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0'
dotenv: .env
networks:
  default: development
  development:
    verify: False
  ganache-local:
    verify: False
  goerli:
    host: https://goerli.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    coin_flip_address: '0xEfF14c6641E89828896591F04Bd15F4F2Da4C8D7'
    telephone_address: '0xd1C24484ee700D94eD81A6201c3e39aBd21b8190'
    token_thing_address: '0xFE5072e945Eef23C35C37a1007A71b6C3810d0c1'
    token_thing_deployer: '0xEf9307fD512C94483A2D672B2306D6751643aF64'
    delegation_address: '0x3A0977753e6D7Ab9CeA61F1E517c5B1280b0dE83'
    force_address: '0x8000AEC6e8cE67161Cd0357aa1C8E4eF2DF171ff'
    vault_address: '0x17bbe11b75Bcf406BD9fD69926905c9B663530a1'
    King_address: '0x8E1211cC38eE55eD7c69B7206AB27Bfcd538AC02'
    Reentrance_address: '0x9AC231885c5f625fA5bD9EaD67312973a4f350B8'
    Elevator_address: '0x7389c04e2f6546C483Ca3CcdeaC003B1318170E9'
    Privacy_address: '0x89E77E68461FC4D52cf2dDc114A67321f3bD6E30'
    GatekeeperOne_address: '0xBA924238FBaa3b36481134cAb670e34974F73Db6'
wallets:
  from_key: ${PRIVATE_KEY}
settings:
  gas_limit: "100000000000"